language: c

os:
  - osx

install:
  - bash ci/install-sbcl.bash
  
script:
# make.sh can't seem to invoke git describe, so do it manually
  - git describe > version.lisp-expr
  - PATH=$PATH:/usr/local/bin sh ./make.sh
  - cd tests && sh run-tests.sh

  
